feat: add rate limit and call policy
zerodevapp/sdk pull request #107
Opened 2024-03-28 13:35 UTC by adnpark

2024-03-28 22:22 UTC, derekchiang requested changes

2024-03-28 22:22 UTC, derekchiang commented on packages/test/v0.7/permissionValidator.test.ts
> +            const signaturePolicy = await toSignaturePolicy({
let's rename this to "signature caller" policy.  So `toSignatureCallerPolicy`.

2024-03-28 22:22 UTC, derekchiang commented on packages/test/v0.7/permissionValidator.test.ts
> +            const rateLimitPolicy = await toRateLimitPolicy({
I suggest adding a more complex use case that leverages all the flags on this policy.

2024-03-29 11:45 UTC, SahilVasava commented on plugins/permission/policies/toSudoPolicy.ts
why was this deleted?

2024-03-29 11:56 UTC, adnpark commented on plugins/permission/policies/toSudoPolicy.ts
ah I asked Taek, and he said that the sudo policy is no longer needed, so I removed it

2024-04-01 09:09 UTC, SahilVasava commented on plugins/permission/policies/toSudoPolicy.ts
Ah! I see. Gonna check.

2024-04-01 11:35 UTC, merged